# Generated by Django 5.1 on 2024-08-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_text", models.TextField()),
                ("edited_text", models.TextField(blank=True, default="")),
                ("send_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
